import { DevPage } from './DevPage';

export const DEV_PAGES: DevPage[] = [
	{
		id               : 1,
		name             : '[PWA_DEMO - ENV_LANDING]',
		framework        : 'Angular',
		frameworkVersion : '17.3.8',
		uixFramework     : 'Material',    
		description      : 'Angular Learning - Landing Page',
		urlPage          : 'https://apereznwo.github.io/PWA_DEMO_ENV_LANDING/',
		urlRepo          : 'https://github.com/aperezNWO/PWA_DEMO_ENV_LANDING.git',
	},
	{
		id               : 2,
		name             : '[PWA_DEMO - ENV_TEST]',
		framework        : 'Angular',
		frameworkVersion : '17.0.8',
		uixFramework     : 'Material',    
		description      : 'Angular Learning - Testing Page',
		urlPage          : 'https://apereznwo.github.io/PWA_DEMO_ENV_TEST/',
		urlRepo          : 'https://github.com/aperezNWO/PWA_DEMO_ENV_TEST.git',
	},
	{
		id               : 3,
		name             : '[PWA_DEMO - ENV_DEV]',
		framework        : 'Angular',
		frameworkVersion : '17.0.8',
		uixFramework     : 'Material',    
		description      : 'Angular Learning - DEV Page',
		urlPage          : 'https://apereznwo.github.io/PWA_DEMO_ENV_DEV/',
		urlRepo          : 'https://github.com/aperezNWO/PWA_DEMO_ENV_DEV.git',
	},
	{
		id               : 4,
		name             : '[PWA_DEMO - ENV_PROD]',
		framework        : 'Angular',
		frameworkVersion : '17.0.8',
		uixFramework     : 'Material',    
		description      : 'Angular Learning - PROD',
		urlPage          : 'https://apereznwo.github.io/PWA_DEMO_ENV_PROD/',
		urlRepo          : 'https://github.com/aperezNWO/PWA_DEMO_ENV_PROD.git',
	},
	{
		id               : 5,
		name             : '[PWA_DEMO - ENV_PUBLIC]',
		framework        : 'Angular',
		frameworkVersion : '17.0.8',
		uixFramework     : 'Material',    
		description      : 'Angular Learning - PUBLIC',
		urlPage          : 'https://apereznwo.github.io/PWA_DEMO_ENV_PUBLIC/',
		urlRepo          : 'https://github.com/aperezNWO/PWA_DEMO_ENV_PUBLIC.git',
	},
	{
		id               : 6,
		name             : '[IONIC DEMO - ENV TEST]',
		framework        : 'Angular',
		frameworkVersion : '17.3.0',
		uixFramework     : 'IONIC',    
		description      : 'IONIC Learning - ENV TEST',
		urlPage          : 'https://apereznwo.github.io/IONIC_DEMO_ENV_TEST/',
		urlRepo          : 'https://github.com/aperezNWO/IONIC_DEMO_ENV_TEST.git',
	},
	{
		id               : 7,
		name             : '[PRIMENG DEMO - QUICKSTART]',
		framework        : 'Angular',
		frameworkVersion : '0.0.0',
		uixFramework     : 'PRIMENG',    
		description      : 'PRIMGENG DEMO - QUICKSTART',
		urlPage          : 'https://apereznwo.github.io/primeng-quickstart-cli/',
		urlRepo          : 'https://github.com/aperezNWO/primeng-quickstart-cli.git',
	},
	{
		id               : 8,
		name             : '[PRIGENG DEMO - ENV PROD]',
		framework        : 'Angular',
		frameworkVersion : '0.0.0',
		uixFramework     : 'PRIMENG',    
		description      : 'PRIMGNG DEMO - ENV PROD',
		urlPage          : 'https://apereznwo.github.io/PRIMENG_DEMO_ENV_PROD/',
		urlRepo          : 'https://github.com/aperezNWO/PRIMENG_DEMO_ENV_PROD.git',
	},
	{
		id               : 9,
		name             : '[NGBOOTRSAP DEMO - ENV TEST]',
		framework        : 'Angular',
		frameworkVersion : '0.0.0',
		uixFramework     : 'NGBOOTSRAP',    
		description      : 'NGBOOTSRAP DEMO - ENV TEST',
		urlPage          : 'https://apereznwo.github.io/NG_BOOTSTRAP_DEMO_ENV_TEST/',
		urlRepo          : 'https://github.com/aperezNWO/NG_BOOTSTRAP_DEMO_ENV_TEST.git',
	},
	{
		id               : 10,
		name             : '[NGBOOTSRAP DEMO - ENV DEV]',
		framework        : 'Angular',
		frameworkVersion : '0.0.0',
		uixFramework     : 'NGBOOTSRAP',    
		description      : 'NGBOOTSRAP DEMO - ENV DEV',
		urlPage          : 'https://apereznwo.github.io/NG_BOOTSTRAP_DEMO_ENV_DEV/',
		urlRepo          : 'https://github.com/aperezNWO/NG_BOOTSTRAP_DEMO_ENV_DEV.git',
	}
];
